spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_lessons
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update

logging:
  file:
    name: logs/log.log
  level:
    root: info

server:
  address: localhost
  port: 8069
