spring.datasource.url=jdbc:mysql://localhost:3306/online_lessons
spring.datasource.username=root
spring.datasource.password=221198stepa
spring.jpa.hibernate.ddl-auto=update
logging.file.name=logs/log.log
logging.level.root=info
