spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_lessons
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: [ GET, POST, PUT, DELETE, OPTIONS ]
      allowed-headers: [ Authorization, Content-Type, Accept ]
      max-age: 3600

logging:
  file:
    name: logs/log.log
  level:
    root: info

server:
  address: localhost
  port: 8069